### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by speqtr** [speqtr/pycute#1]
**TODO:**
- [x] Add `README.md`;
- [x] Add `LICENSE.txt` (LGPLv3);
- [x] Setup python3 virtualenv using pipenv;
- [x] Setup very basic cmake project;
- [x] Add `.gitignore` file.

**NOTE:** This is just a very basic project structure setup. Nothing fancy.

**Comment by speqtr** [comment]
Related changes were recently pushed to `nightly` branch. Issue can be closed.
