### ISSUE TITLE
Implement PyQmlPlugin

### ISSUE THREAD

**Issue by speqtr** [speqtr/pycute#3]
**TODO:**
- [x] Add cmake script for `python` setup;
- [x] Add cmake script for `Qt5` setup;
- [x] Add cmake script for `pybind11` setup;
- [ ] Implement `pyqmlplugin` library.
